### ISSUE TITLE
Transfer to JuliaDiffEq?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/RootedTrees.jl#1]
@YingboMa is interested in taking this all the way to automated optimization kernel generation. We were trying this with ModelingToolkit.jl and it's working pretty well, so we were wondering if you'd like to transfer it over to JuliaDiffEq so we could start hacking away at it.

**Comment by ranocha** [comment]
Certainly, that's fine for me. How do we proceed?

**Comment by ChrisRackauckas** [comment]
Indeed, I think we'll be taking a optimizing some of it, documenting it, and building some new features around it. It's good stuff.

**Comment by ChrisRackauckas** [comment]
CI is transferred and the badges are updated.
