### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by ranocha** [JuliaDiffEq/RootedTrees.jl#9]
I've added some additional functionality in the last days but do not plan to add more in the next few days. Shall/can we release a new version?
How shall we generally proceed with releasing a new version?

**Comment by ChrisRackauckas** [comment]
Release when you need to. If a repo is sitting for a bit with some unreleased commits I usually make sure they end up released.

**Comment by ranocha** [comment]
Okay, thanks.

**Comment by ranocha** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()
